"""add provider

Revision ID: 8e30bf9bb207
Revises: 3af2de274b82
Create Date: 2023-09-05 20:48:55.922140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e30bf9bb207'
down_revision: Union[str, None] = '3af2de274b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('provider', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['id'])
    op.create_unique_constraint(None, 'type_subscribes', ['id'])
    op.create_unique_constraint(None, 'user_subscribes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_subscribes', type_='unique')
    op.drop_constraint(None, 'type_subscribes', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'provider')
    # ### end Alembic commands ###
